### PR TITLE
Branchday2

### PR DESCRIPTION
**Pull request by alexavanhooser**
Here's my homework from day 2.

### CODE REVIEW

**Comment by ryekerjh** [comment]
@alexavanhooser it looks like you have a slight error on line 14 of your index.html, in your class name. Fix that piece and push the fix, then retag me and I'll approve the merge. Great work!!

**Comment by ryekerjh** [comment]
@alexavanhooser You will have to add me as a contributor (we cover that tonight) in order to allow me to review your PR. You have some conflicts, so _don't_ merge this yet.

**Comment by alexavanhooser** [comment]
Okay, cool. Will you work with me during our break?

**Comment by ryekerjh** [comment]
@alexavanhooser Looks good, I think you did your day 2 stuff on your day 1 repository and then tried to force the two things to merge. you can close this PR 👍

**Pull request merged**
